### ISSUE TITLE
debconf: unable to initialize frontend: Dialog docker ubuntu

### ISSUE THREAD

**Issue by TonnyCZ** [lvhengani/sen2cor_docker#1]
Hi!
During the build I get:
debconf: unable to initialize frontend: Dialog docker ubuntu

This helps:
ENV DEBIAN_FRONTEND noninteractive

Please add this to Dockerfile.
Thanks a lot!

**Comment by lvhengani** [comment]
Thank you TonnyCZ, I have updated the Dockerfile.
Did you run it successfully?

**Comment by TonnyCZ** [comment]
Yes - it run perfectly, good work!
Thank you!
